-- The design, the piece, and when the piece counts as dead.
--
-- Three things the meeting asked for, all in the same part of the model.
--
-- STYLE NUMBER — the design, above the SKU. One style is made in several sizes
-- and weights, each its own SKU and each its own piece on the shelf. "How is
-- this design selling" and "how is this exact piece selling" are different
-- questions and only the second one could be asked. Deliberately NOT unique:
-- many products sharing a style number is the whole point.
--
-- VIN — the piece's own identifier, generated by us. Every other code on a piece
-- belongs to somebody else: the SKU is the design, the HUID is BIS's, the
-- certificate number is the lab's, the legacy id is the old ERP's. None of them
-- identifies THIS piece in a way we control, and the SKU is shared across
-- identical pieces. Nullable, because every piece that already exists has none
-- and inventing them retroactively would print a number the physical tag does
-- not carry.
--
-- DEAD STOCK — 180 days was a constant in two places and wrong for everybody. A
-- chain moves in weeks; a bridal set is expected to sit. One threshold across
-- both makes the figure either alarm about normal inventory or say nothing.
--
-- All additive. With no policy rows the platform default still applies, so
-- nothing changes for a tenant until somebody configures it.

ALTER TABLE "Product" ADD COLUMN "styleNumber" TEXT;
ALTER TABLE "StockItem" ADD COLUMN "styleNumber" TEXT;
ALTER TABLE "StockItem" ADD COLUMN "vin" TEXT;

-- Unique per tenant. Two pieces sharing one VIN is the single thing that would
-- make the number worthless. NULLs are distinct in Postgres, so every existing
-- piece is unaffected.
CREATE UNIQUE INDEX "StockItem_organisationId_vin_key" ON "StockItem"("organisationId", "vin");

CREATE INDEX "Product_organisationId_styleNumber_idx" ON "Product"("organisationId", "styleNumber");
CREATE INDEX "StockItem_organisationId_styleNumber_idx" ON "StockItem"("organisationId", "styleNumber");

CREATE TABLE "DeadStockPolicy" (
    "id" TEXT NOT NULL,
    "organisationId" TEXT NOT NULL,
    -- NULL = the tenant's default for anything without its own rule.
    "category" "ProductCategory",
    "thresholdDays" INTEGER NOT NULL,
    -- NULL = no warning band. The honest answer for a tenant that wants one line.
    "warnAfterDays" INTEGER,
    "updatedById" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "DeadStockPolicy_pkey" PRIMARY KEY ("id")
);

-- One rule per category. Enforced here rather than in code because two
-- contradictory rules is not a state anything downstream could resolve.
CREATE UNIQUE INDEX "DeadStockPolicy_organisationId_category_key"
    ON "DeadStockPolicy"("organisationId", "category");

-- And exactly one DEFAULT.
--
-- The index above does not give us this: Postgres treats NULLs as distinct, so
-- (org, NULL) can be inserted any number of times and the tenant would end up
-- with several contradictory defaults and no way to say which one won. A partial
-- index is the only way to express "at most one row whose category is null", and
-- Prisma's schema language cannot declare it — which is why it lives here, and
-- why this comment exists rather than the constraint looking redundant.
CREATE UNIQUE INDEX "DeadStockPolicy_organisationId_default_key"
    ON "DeadStockPolicy"("organisationId")
    WHERE "category" IS NULL;

ALTER TABLE "DeadStockPolicy"
    ADD CONSTRAINT "DeadStockPolicy_organisationId_fkey"
    FOREIGN KEY ("organisationId") REFERENCES "Organisation"("id")
    ON DELETE RESTRICT ON UPDATE CASCADE;
